In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Ans: Yes there is differenec between the data type of both the variables. list_ variable is of list type which contains list of string values,
whereas array_list is an numpy array having unassigned values. 

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

In [8]:
array_list.dtype

dtype('<U1')

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
for i in list_:
    print(i ," is of",type(i))

1  is of <class 'str'>
2  is of <class 'str'>
3  is of <class 'str'>
4  is of <class 'str'>
5  is of <class 'str'>


In [10]:
for i in array_list:
    print(i, " is of type",type(i))

1  is of type <class 'numpy.str_'>
2  is of type <class 'numpy.str_'>
3  is of type <class 'numpy.str_'>
4  is of type <class 'numpy.str_'>
5  is of type <class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Ans: Yes there will be difference between the data type of the element present in list_ and array_list variable.
list_ is a list variable containing the string values whereas array_list is the numpy array containing the int values.

In [12]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [13]:
for i in list_:
    print(i ," is of",type(i))

1  is of <class 'str'>
2  is of <class 'str'>
3  is of <class 'str'>
4  is of <class 'str'>
5  is of <class 'str'>


In [14]:
for i in array_list:
    print(i, " is of type",type(i))

1  is of type <class 'numpy.int64'>
2  is of type <class 'numpy.int64'>
3  is of type <class 'numpy.int64'>
4  is of type <class 'numpy.int64'>
5  is of type <class 'numpy.int64'>


In [17]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [19]:
num_array.shape

(2, 3)

In [20]:
num_array.size

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
x=np.zeros((3,3),dtype=int)
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
x.shape

(3, 3)

In [28]:
x.size

9

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [33]:
y=np.identity(5,dtype=int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
y.shape

(5, 5)